# Generated by Django 3.2.7 on 2021-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20210916_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
