# Generated by Django 3.2.7 on 2021-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20210916_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
