# Generated by Django 3.2.7 on 2021-09-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='orig_comment',
        ),
    ]
